terraformer planet field bonus logic
lanedirt/OGameX pull request #412
Opened 2024-10-23 23:50 UTC by jackbayliss

This should handle #392 

Also adds a variety of tests - feel free to let me know any adjustments.

2024-10-24 17:54 UTC, lanedirt requested changes
Hi @jackbayliss,

Changes look good to me! I just have a few small whiteline nitpicks to make it a little bit cleaner and conform to the rest of the codebase. Could you take a look at these?

Other than these minor style tweaks, functionality looks to be working great. Thanks for your work on this! 🚀

2024-10-24 17:54 UTC, lanedirt commented on app/Services/PlanetService.php
> +
Nitpick: can you remove the duplicate whiteline.

2024-10-24 17:54 UTC, lanedirt commented on tests/Unit/PlanetServiceTest.php
> +
Nitpick: can you remove the whiteline at the start of the method.

2024-10-24 17:54 UTC, lanedirt commented on tests/Unit/PlanetServiceTest.php
> +
Nitpick: can you remove the duplicate whiteline.

2024-10-24 17:54 UTC, lanedirt commented on tests/Unit/PlanetServiceTest.php
> +    }
Nitpick: can you add a whiteline here between the function closing brace and the phpdoc comment of the next function.

2024-10-24 20:26 UTC, jackbayliss commented
@lanedirt  Should hopefully now be sorted, did spot a previous test I did where I missed a whitespace after the closing brace, so sorted that too.

2024-10-25 08:11 UTC, lanedirt requested changes
Hi @jackbayliss,

Thanks for the refactor! In the latest diff, I noticed a duplicate blank line that still remains. Could you take a look at this?

By the way, I'll try to see if I can incorporate these style checks into the PSR/PhpStan code analysis so that the build process can automatically detect them. That should make things easier going forward.

Thanks again for your work and time 😄 !

2024-10-25 08:11 UTC, lanedirt commented on tests/Unit/PlanetServiceTest.php
> +
Nitpick: there is one duplicate whiteline remaining here.

2024-10-25 08:16 UTC, jackbayliss commented
@lanedirt  Good catch, must of missed it- I've now adjusted it.

It would be ideal if we could add this into the code analysis as I guess everyone has their own style 😃

2024-10-25 08:17 UTC, lanedirt approved these changes
LGTM!

2024-10-25 08:22 UTC, jackbayliss commented
Not sure why the test failed! Looks to be a bit flaky, but I believe this is already in another issue?

2024-10-25 08:25 UTC, lanedirt commented
> Not sure why the test failed! Looks to be a bit flaky, but I believe this is already in another issue?

Yes it looks like its the same issue as reported in #401. Have to look into fixing that one soon. 🐛  Re-running tests now.

2024-10-25 08:30 UTC, merged