fixed #156 fixed #155 fixed #494
lanedirt/OGameX pull request #509
Opened 2024-12-26 12:44 UTC by yazilimmz

fixed #156 fixed #155 fixed #494

Reverse engineering was used for deuterium calculation.
Errors in flight durations were resolved.
The issue in flight distance calculation was fixed.
The circular universe, which has become standard in the normal game, was activated.
In deployment, when a fleet is deployed, it now leaves half of the deuterium on the target planet, just like in the original game.
A few more fixes were also made. :)

2024-12-26 15:47 UTC, yazilimmz commented
"The tests don't give any errors on my side either. Can you please try it on your side, @lanedirt ?

> www@d1dd6a39b15e:/var/www$ ./vendor/bin/phpunit
> PHPUnit 11.5.1 by Sebastian Bergmann and contributors.
> 
> Runtime:       PHP 8.4.2
> Configuration: /var/www/phpunit.xml
> 
> ....................................."Moon was created after amount of attempts: 1" // tests/Feature/FleetDispatch/FleetDispatchAttackTest.php:945
> ..........................  63 / 208 ( 30%)
> ............................................................... 126 / 208 ( 60%)
> ............................................................... 189 / 208 ( 90%)
> ...................                                             208 / 208 (100%)
> 
> Time: 04:12.284, Memory: 250.50 MB
> 
> OK (208 tests, 2782 assertions)

2024-12-26 21:51 UTC, jackbayliss commented on app/Services/FleetMissionService.php
> +        // Eğer galaksiler farklıysa
Can these be English? Seeing as the rest of the comments are :)

2024-12-26 22:58 UTC, jackbayliss commented on -
This is an empty file, and not needed :)

2024-12-26 23:01 UTC, jackbayliss commented on app/Services/FleetMissionService.php
> +        // Eğer galaksiler farklıysa
Same for other comments

2024-12-26 23:47 UTC, jackbayliss commented on app/Services/FleetMissionService.php
> +    public function calcConsumption(PlanetService $fromPlanet, UnitCollection $ships, Coordinate $target_coordinate, int $holdingTime, float $speed_percent)
```suggestion
    public function calculateConsumption(PlanetService $fromPlanet, UnitCollection $ships, Coordinate $target_coordinate, int $holdingTime, float $speed_percent)
```
This should probably be calculate, like the other methods :)

2024-12-27 00:30 UTC, jackbayliss commented
@yazilimmz  The test that is failing is the `php artisan test:race-condition-unitqueue` test, if you run this command locally (via the php container) you should see the same error :)

2024-12-27 06:48 UTC, yazilimmz commented
> @yazilimmz The test that is failing is the `php artisan test:race-condition-unitqueue` test, if you run this command locally (via the php container) you should see the same error :)

Yesterday, I was getting an error in a PHPUnit test.

The same thing happened again.

While Git throws an error, the test passes successfully on my local machine.

The test error given by Git:

> ----------------------------------------------------------------------------------
> 
> Not enough resources on the planet to send the fleet.
> 
>   at tests/FleetDispatchTestCase.php:246
>     242▕             'speed' => 10,
>     243▕             ...$unitsArray
>     244▕         ]);
>     245▕ 
>   ➜ 246▕         $post->assertStatus($assertStatus);
>     247▕ 
>     248▕         $this->reloadApplication();
>     249▕ 
>     250▕         $this->get('/ajax/fleet/eventbox/fetch')->assertStatus(200);
> 
>   1   tests/FleetDispatchTestCase.php:143
>   2   tests/Feature/FleetDispatch/FleetDispatchAttackTest.php:676
> 
> 

However, this test passes successfully on my side, and I get 208 passed tests.

2024-12-27 09:56 UTC, lanedirt requested changes
Hi @yazilimmz,

Thanks for the changes! Looks impressive and quite in-depth. 👍 And thanks @jackbayliss for your initial review, I agree with the comments. I found two more small things, can you check these?

I'll also try and see if I can reproduce the test error on my environment locally. I'll see if I can do this tonight.

2024-12-27 09:56 UTC, lanedirt commented on app/Services/FleetMissionService.php
> +
Can you update these comments to be in english

2024-12-27 09:56 UTC, lanedirt commented on tests/Feature/FleetDispatch/FleetDispatchGenericTest.php
> +        $this->assertEquals(4788, $fleetMissionService->calculateFleetMissionDuration($this->planetService, $targetPlanetCoords, $units));
Can you update the comment stating how long the fleet is expected to take (in hour:minute:second format)

2024-12-27 16:20 UTC, lanedirt commented
Hi @yazilimmz,

I checked the tests on my local environment and I got the error like 50% of the time when I ran the tests 10 times. I think it has to do with the deuterium costs especially with the `testLargeScaleAttackWithDebrisField()` method.


This test method sends a fleet to a random planet within a range of -15 systems to +15 systems. The test itself sends a fleet of 700k cruisers and 100k battleships. Based on this new code if I try to send this fleet to a planet 15 systems away the deuterium cost is 105M:

<img width="656" alt="Screenshot 2024-12-27 at 17 15 14" src="https://github.com/user-attachments/assets/54e1e355-e131-4622-bf8e-638d6aa307f4" />

And the test currently provides only 100M starting deuterium costs:
```
    public function testLargeScaleAttackWithDebrisField(): void
    {
        // Prepare attacker fleet
        $this->planetAddUnit('cruiser', 700000);
        $this->planetAddUnit('battle_ship', 100000);

        $this->planetAddResources(new Resources(5000, 5000, 100000000, 0));
```

So because of the random nature of the tests I think if we increase the deuterium on the planet at the start of the test this issue should be solved. Probably good to set it to like 150M to be safe?

2024-12-27 16:55 UTC, yazilimmz commented
> Hi @yazilimmz,
> 
> I checked the tests on my local environment and I got the error like 50% of the time when I ran the tests 10 times. I think it has to do with the deuterium costs especially with the `testLargeScaleAttackWithDebrisField()` method.
> 
> This test method sends a fleet to a random planet within a range of -15 systems to +15 systems. The test itself sends a fleet of 700k cruisers and 100k battleships. Based on this new code if I try to send this fleet to a planet 15 systems away the deuterium cost is 105M:
> 
> <img alt="Screenshot 2024-12-27 at 17 15 14" width="656" src="https://private-user-images.githubusercontent.com/6917405/398972592-54e1e355-e131-4622-bf8e-638d6aa307f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMTY3MjAsIm5iZiI6MTczNTMxNjQyMCwicGF0aCI6Ii82OTE3NDA1LzM5ODk3MjU5Mi01NGUxZTM1NS1lMTMxLTQ2MjItYmY4ZS02MzhkNmFhMzA3ZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjdUMTYyMDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmYxNTBhOGQ4Zjg3NWJlNjQ1OTA0YmVmMjU0YjBiMGQ3ZTQ1NmZiYjM0ZmM2OWRlMDZiMjZmNjk5MGVlOWNhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1L2lr0iWBkFn6A6_FcaCXHn3NWyeNFhGK0HcJtGqafU">
> And the test currently provides only 100M starting deuterium costs:
> 
> ```
>     public function testLargeScaleAttackWithDebrisField(): void
>     {
>         // Prepare attacker fleet
>         $this->planetAddUnit('cruiser', 700000);
>         $this->planetAddUnit('battle_ship', 100000);
> 
>         $this->planetAddResources(new Resources(5000, 5000, 100000000, 0));
> ```
> 
> So because of the random nature of the tests I think if we increase the deuterium on the planet at the start of the test this issue should be solved. Probably good to set it to like 150M to be safe?

Nice approach, I hadn’t noticed the +15 -15 situation. I updated the code again. Thank you

2024-12-27 17:33 UTC, lanedirt commented
LGTM! One test failed but that one has been flaky for longer so probably doesn't have to do with this change. Merging the PR!

Thanks again for your work and contribution 😄 !

2024-12-27 17:33 UTC, merged